---
env:
  es2021: true
  node: true
  jest: true

plugins:
  - jest

extends:
  - airbnb-base
  - plugin:jest/recommended

parserOptions:
  ecmaVersion: 12 #в образце Хекслет была 11 версия, но в июне 2021 вышла 12 версия стандарта
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0 # FIXME: remove when rule will be adjusted for new nodejs version
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }] 